In [4]:
# Expernetic Data Engineer Internship Assignment
# Notebook 01: Dataset Familiarization
# Author:NithyaSagar
# Cities: London, New York

In [5]:
import pandas as pd
import numpy as np

In [6]:
london_listings = pd.read_csv("../data/raw/london/listings.csv.gz")
london_calendar = pd.read_csv("../data/raw/london/calendar.csv.gz")
london_reviews = pd.read_csv("../data/raw/london/reviews.csv.gz")
london_neighbourhoods = pd.read_csv("../data/raw/london/neighbourhoods.csv")

ny_listings = pd.read_csv("../data/raw/new_york/listings.csv.gz")
ny_calendar = pd.read_csv("../data/raw/new_york/calendar.csv.gz")
ny_reviews = pd.read_csv("../data/raw/new_york/reviews.csv.gz")
ny_neighbourhoods = pd.read_csv("../data/raw/new_york/neighbourhoods.csv")

In [7]:
datasets = {
    "London Listings": london_listings,
    "London Calendar": london_calendar,
    "London Reviews": london_reviews,
    "London Neighbourhoods": london_neighbourhoods,
    "NY Listings": ny_listings,
    "NY Calendar": ny_calendar,
    "NY Reviews": ny_reviews,
    "NY Neighbourhoods": ny_neighbourhoods
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

London Listings: (96871, 79)
London Calendar: (35357974, 7)
London Reviews: (2097996, 6)
London Neighbourhoods: (33, 2)
NY Listings: (35036, 90)
NY Calendar: (12788141, 5)
NY Reviews: (1003299, 6)
NY Neighbourhoods: (230, 2)

In [8]:
def schema_report(df, dataset_name):
    report = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str).values,
        "Missing Values": df.isnull().sum().values,
        "Missing %": round((df.isnull().sum() / len(df)) * 100, 2).values,
        "Unique Values": [df[col].nunique() for col in df.columns]
    })

    print(f"\n{'='*60}")
    print(dataset_name)
    print('='*60)

    display(report)

    return report

In [9]:
london_listing_schema = schema_report(
    london_listings,
    "London Listings"
)

ny_listing_schema = schema_report(
    ny_listings,
    "New York Listings"
)

============================================================
London Listings
============================================================

,Column,Data Type,Missing Values,Missing %,Unique Values
0,id,int64,0,0.0,96871
1,listing_url,str,0,0.0,96871
2,scrape_id,int64,0,0.0,1
3,last_scraped,str,0,0.0,5
4,source,str,0,0.0,2
...,...,...,...,...,...
74,calculated_host_listings_count,int64,0,0.0,98
75,calculated_host_listings_count_entire_homes,int64,0,0.0,87
76,calculated_host_listings_count_private_rooms,int64,0,0.0,46
77,calculated_host_listings_count_shared_rooms,int64,0,0.0,13
78,reviews_per_month,float64,24122,24.9,910

============================================================
New York Listings
============================================================

,Column,Data Type,Missing Values,Missing %,Unique Values
0,id,int64,0,0.00,35036
1,listing_url,str,0,0.00,35036
2,scrape_id,int64,0,0.00,1
3,last_scraped,str,0,0.00,3
4,source,str,0,0.00,2
...,...,...,...,...,...
85,calculated_host_listings_count,int64,0,0.00,66
86,calculated_host_listings_count_entire_homes,int64,0,0.00,55
87,calculated_host_listings_count_private_rooms,int64,0,0.00,40
88,calculated_host_listings_count_shared_rooms,int64,0,0.00,10
89,reviews_per_month,float64,10494,29.95,784

In [10]:
london_listings.info()
ny_listings.info()

london_listings.head(3)
ny_listings.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 96871 entries, 0 to 96870
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            96871 non-null  int64
 1   listing_url                                   96871 non-null  str
 2   scrape_id                                     96871 non-null  int64
 3   last_scraped                                  96871 non-null  str
 4   source                                        96871 non-null  str
 5   name                                          96871 non-null  str
 6   description                                   94421 non-null  str
 7   neighborhood_overview                         41208 non-null  str
 8   picture_url                                   96865 non-null  str
 9   host_id                                       96871 non-null  int64
 10  host_url                                      96871 non-null  str
 11  host_name                                     96828 non-null  str
 12  host_since                                    96830 non-null  str
 13  host_location                                 73100 non-null  str
 14  host_about                                    49833 non-null  str
 15  host_response_time                            65164 non-null  str
 16  host_response_rate                            65164 non-null  str
 17  host_acceptance_rate                          69111 non-null  str
 18  host_is_superhost                             95105 non-null  str
 19  host_thumbnail_url                            96830 non-null  str
 20  host_picture_url                              96830 non-null  str
 21  host_neighbourhood                            45850 non-null  str
 22  host_listings_count                           96830 non-null  float64
 23  host_total_listings_count                     96830 non-null  float64
 24  host_verifications                            96830 non-null  str
 25  host_has_profile_pic                          96830 non-null  str
 26  host_identity_verified                        96830 non-null  str
 27  neighbourhood                                 41209 non-null  str
 28  neighbourhood_cleansed                        96871 non-null  str
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      96871 non-null  float64
 31  longitude                                     96871 non-null  float64
 32  property_type                                 96871 non-null  str
 33  room_type                                     96871 non-null  str
 34  accommodates                                  96871 non-null  int64
 35  bathrooms                                     62025 non-null  float64
 36  bathrooms_text                                96718 non-null  str
 37  bedrooms                                      84096 non-null  float64
 38  beds                                          61951 non-null  float64
 39  amenities                                     96871 non-null  str
 40  price                                         61963 non-null  str
 41  minimum_nights                                96871 non-null  int64
 42  maximum_nights                                96871 non-null  int64
 43  minimum_minimum_nights                        96868 non-null  float64
 44  maximum_minimum_nights                        96868 non-null  float64
 45  minimum_maximum_nights                        96868 non-null  float64
 46  maximum_maximum_nights                        96868 non-null  float64
 47  minimum_nights_avg_ntm                        96871 non-null  float64
 48  maximum_nights_avg_ntm                        96871 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              92622 non-null  str
 51  availability_30                               96871 non-null  int64
 52  availability_60                               96871 non-null  int64
 53  availability_90                               96871 non-null  int64
 54  availability_365                              96871 non-null  int64
 55  calendar_last_scraped                         96871 non-null  str
 56  number_of_reviews                             96871 non-null  int64
 57  number_of_reviews_ltm                         96871 non-null  int64
 58  number_of_reviews_l30d                        96871 non-null  int64
 59  availability_eoy                              96871 non-null  int64
 60  number_of_reviews_ly                          96871 non-null  int64
 61  estimated_occupancy_l365d                     96871 non-null  int64
 62  estimated_revenue_l365d                       61963 non-null  float64
 63  first_review                                  72749 non-null  str
 64  last_review                                   72749 non-null  str
 65  review_scores_rating                          72749 non-null  float64
 66  review_scores_accuracy                        72734 non-null  float64
 67  review_scores_cleanliness                     72740 non-null  float64
 68  review_scores_checkin                         72706 non-null  float64
 69  review_scores_communication                   72729 non-null  float64
 70  review_scores_location                        72705 non-null  float64
 71  review_scores_value                           72705 non-null  float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              96871 non-null  str
 74  calculated_host_listings_count                96871 non-null  int64
 75  calculated_host_listings_count_entire_homes   96871 non-null  int64
 76  calculated_host_listings_count_private_rooms  96871 non-null  int64
 77  calculated_host_listings_count_shared_rooms   96871 non-null  int64
 78  reviews_per_month                             72749 non-null  float64
dtypes: float64(25), int64(20), str(34)
memory usage: 58.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 35036 entries, 0 to 35035
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            35036 non-null  int64
 1   listing_url                                   35036 non-null  str
 2   scrape_id                                     35036 non-null  int64
 3   last_scraped                                  35036 non-null  str
 4   source                                        35036 non-null  str
 5   name                                          35034 non-null  str
 6   description                                   33517 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   34901 non-null  str
 9   host_id                                       35036 non-null  int64
 10  host_url                                      35036 non-null  str
 11  host_profile_id                               34196 non-null  float64
 12  host_profile_url                              34132 non-null  str
 13  host_name                                     34201 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      34196 non-null  float64
 16  hosts_time_as_user_months                     34196 non-null  float64
 17  hosts_time_as_host_years                      34196 non-null  float64
 18  hosts_time_as_host_months                     34196 non-null  float64
 19  host_location                                 27029 non-null  str
 20  host_about                                    19647 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             34196 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              34196 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           34196 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          34195 non-null  str
 32  host_identity_verified                        34196 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        35036 non-null  str
 35  neighbourhood_group_cleansed                  35036 non-null  str
 36  latitude                                      35036 non-null  float64
 37  longitude                                     35036 non-null  float64
 38  property_type                                 35036 non-null  str
 39  room_type                                     35036 non-null  str
 40  accommodates                                  35036 non-null  int64
 41  bathrooms                                     3797 non-null   float64
 42  bathrooms_text                                34918 non-null  str
 43  bedrooms                                      22972 non-null  float64
 44  beds                                          3761 non-null   float64
 45  amenities                                     35036 non-null  str
 46  price                                         20693 non-null  str
 47  price_quote_checkin_date                      21921 non-null  str
 48  price_quote_checkout_date                     21921 non-null  str
 49  price_quote_total_price                       20693 non-null  float64
 50  price_quote_price_per_night                   20693 non-null  float64
 51  price_quote_raw                               21921 non-null  str
 52  minimum_nights                                35033 non-null  float64
 53  maximum_nights                                35033 non-null  float64
 54  minimum_minimum_nights                        35033 non-null  float64
 55  maximum_minimum_nights                        35033 non-null  float64
 56  minimum_maximum_nights                        35033 non-null  float64
 57  maximum_maximum_nights                        35033 non-null  float64
 58  minimum_nights_avg_ntm                        35036 non-null  float64
 59  maximum_nights_avg_ntm                        35036 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29409 non-null  str
 62  availability_30                               35036 non-null  int64
 63  availability_60                               35036 non-null  int64
 64  availability_90                               35036 non-null  int64
 65  availability_365                              35036 non-null  int64
 66  calendar_last_scraped                         35036 non-null  str
 67  number_of_reviews                             35036 non-null  int64
 68  number_of_reviews_ltm                         35036 non-null  int64
 69  number_of_reviews_l30d                        35036 non-null  int64
 70  availability_eoy                              35036 non-null  int64
 71  number_of_reviews_ly                          35036 non-null  int64
 72  estimated_occupancy_l365d                     35036 non-null  int64
 73  estimated_revenue_l365d                       20693 non-null  float64
 74  first_review                                  24542 non-null  str
 75  last_review                                   24542 non-null  str
 76  review_scores_rating                          24542 non-null  float64
 77  review_scores_accuracy                        24532 non-null  float64
 78  review_scores_cleanliness                     24541 non-null  float64
 79  review_scores_checkin                         24528 non-null  float64
 80  review_scores_communication                   24536 non-null  float64
 81  review_scores_location                        24525 non-null  float64
 82  review_scores_value                           24526 non-null  float64
 83  license                                       5062 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                35036 non-null  int64
 86  calculated_host_listings_count_entire_homes   35036 non-null  int64
 87  calculated_host_listings_count_private_rooms  35036 non-null  int64
 88  calculated_host_listings_count_shared_rooms   35036 non-null  int64
 89  reviews_per_month                             24542 non-null  float64
dtypes: float64(42), int64(18), str(30)
memory usage: 24.1 MB

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6848,https://www.airbnb.com/rooms/6848,20260414135910,2026-04-14,previous scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.59,NaN,NaN,1,1,0,0,0.96
1,6872,https://www.airbnb.com/rooms/6872,20260414135910,2026-04-14,previous scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.00,5.00,5.00,NaN,NaN,2,0,2,0,0.04
2,6990,https://www.airbnb.com/rooms/6990,20260414135910,2026-04-14,previous scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,NaN,https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.84,NaN,NaN,1,0,1,0,1.25

In [11]:
london_listings.info()
ny_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 96871 entries, 0 to 96870
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            96871 non-null  int64
 1   listing_url                                   96871 non-null  str
 2   scrape_id                                     96871 non-null  int64
 3   last_scraped                                  96871 non-null  str
 4   source                                        96871 non-null  str
 5   name                                          96871 non-null  str
 6   description                                   94421 non-null  str
 7   neighborhood_overview                         41208 non-null  str
 8   picture_url                                   96865 non-null  str
 9   host_id                                       96871 non-null  int64
 10  host_url                                      96871 non-null  str
 11  host_name                                     96828 non-null  str
 12  host_since                                    96830 non-null  str
 13  host_location                                 73100 non-null  str
 14  host_about                                    49833 non-null  str
 15  host_response_time                            65164 non-null  str
 16  host_response_rate                            65164 non-null  str
 17  host_acceptance_rate                          69111 non-null  str
 18  host_is_superhost                             95105 non-null  str
 19  host_thumbnail_url                            96830 non-null  str
 20  host_picture_url                              96830 non-null  str
 21  host_neighbourhood                            45850 non-null  str
 22  host_listings_count                           96830 non-null  float64
 23  host_total_listings_count                     96830 non-null  float64
 24  host_verifications                            96830 non-null  str
 25  host_has_profile_pic                          96830 non-null  str
 26  host_identity_verified                        96830 non-null  str
 27  neighbourhood                                 41209 non-null  str
 28  neighbourhood_cleansed                        96871 non-null  str
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      96871 non-null  float64
 31  longitude                                     96871 non-null  float64
 32  property_type                                 96871 non-null  str
 33  room_type                                     96871 non-null  str
 34  accommodates                                  96871 non-null  int64
 35  bathrooms                                     62025 non-null  float64
 36  bathrooms_text                                96718 non-null  str
 37  bedrooms                                      84096 non-null  float64
 38  beds                                          61951 non-null  float64
 39  amenities                                     96871 non-null  str
 40  price                                         61963 non-null  str
 41  minimum_nights                                96871 non-null  int64
 42  maximum_nights                                96871 non-null  int64
 43  minimum_minimum_nights                        96868 non-null  float64
 44  maximum_minimum_nights                        96868 non-null  float64
 45  minimum_maximum_nights                        96868 non-null  float64
 46  maximum_maximum_nights                        96868 non-null  float64
 47  minimum_nights_avg_ntm                        96871 non-null  float64
 48  maximum_nights_avg_ntm                        96871 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              92622 non-null  str
 51  availability_30                               96871 non-null  int64
 52  availability_60                               96871 non-null  int64
 53  availability_90                               96871 non-null  int64
 54  availability_365                              96871 non-null  int64
 55  calendar_last_scraped                         96871 non-null  str
 56  number_of_reviews                             96871 non-null  int64
 57  number_of_reviews_ltm                         96871 non-null  int64
 58  number_of_reviews_l30d                        96871 non-null  int64
 59  availability_eoy                              96871 non-null  int64
 60  number_of_reviews_ly                          96871 non-null  int64
 61  estimated_occupancy_l365d                     96871 non-null  int64
 62  estimated_revenue_l365d                       61963 non-null  float64
 63  first_review                                  72749 non-null  str
 64  last_review                                   72749 non-null  str
 65  review_scores_rating                          72749 non-null  float64
 66  review_scores_accuracy                        72734 non-null  float64
 67  review_scores_cleanliness                     72740 non-null  float64
 68  review_scores_checkin                         72706 non-null  float64
 69  review_scores_communication                   72729 non-null  float64
 70  review_scores_location                        72705 non-null  float64
 71  review_scores_value                           72705 non-null  float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              96871 non-null  str
 74  calculated_host_listings_count                96871 non-null  int64
 75  calculated_host_listings_count_entire_homes   96871 non-null  int64
 76  calculated_host_listings_count_private_rooms  96871 non-null  int64
 77  calculated_host_listings_count_shared_rooms   96871 non-null  int64
 78  reviews_per_month                             72749 non-null  float64
dtypes: float64(25), int64(20), str(34)
memory usage: 58.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 35036 entries, 0 to 35035
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            35036 non-null  int64
 1   listing_url                                   35036 non-null  str
 2   scrape_id                                     35036 non-null  int64
 3   last_scraped                                  35036 non-null  str
 4   source                                        35036 non-null  str
 5   name                                          35034 non-null  str
 6   description                                   33517 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   34901 non-null  str
 9   host_id                                       35036 non-null  int64
 10  host_url                                      35036 non-null  str
 11  host_profile_id                               34196 non-null  float64
 12  host_profile_url                              34132 non-null  str
 13  host_name                                     34201 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      34196 non-null  float64
 16  hosts_time_as_user_months                     34196 non-null  float64
 17  hosts_time_as_host_years                      34196 non-null  float64
 18  hosts_time_as_host_months                     34196 non-null  float64
 19  host_location                                 27029 non-null  str
 20  host_about                                    19647 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             34196 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              34196 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           34196 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          34195 non-null  str
 32  host_identity_verified                        34196 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        35036 non-null  str
 35  neighbourhood_group_cleansed                  35036 non-null  str
 36  latitude                                      35036 non-null  float64
 37  longitude                                     35036 non-null  float64
 38  property_type                                 35036 non-null  str
 39  room_type                                     35036 non-null  str
 40  accommodates                                  35036 non-null  int64
 41  bathrooms                                     3797 non-null   float64
 42  bathrooms_text                                34918 non-null  str
 43  bedrooms                                      22972 non-null  float64
 44  beds                                          3761 non-null   float64
 45  amenities                                     35036 non-null  str
 46  price                                         20693 non-null  str
 47  price_quote_checkin_date                      21921 non-null  str
 48  price_quote_checkout_date                     21921 non-null  str
 49  price_quote_total_price                       20693 non-null  float64
 50  price_quote_price_per_night                   20693 non-null  float64
 51  price_quote_raw                               21921 non-null  str
 52  minimum_nights                                35033 non-null  float64
 53  maximum_nights                                35033 non-null  float64
 54  minimum_minimum_nights                        35033 non-null  float64
 55  maximum_minimum_nights                        35033 non-null  float64
 56  minimum_maximum_nights                        35033 non-null  float64
 57  maximum_maximum_nights                        35033 non-null  float64
 58  minimum_nights_avg_ntm                        35036 non-null  float64
 59  maximum_nights_avg_ntm                        35036 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29409 non-null  str
 62  availability_30                               35036 non-null  int64
 63  availability_60                               35036 non-null  int64
 64  availability_90                               35036 non-null  int64
 65  availability_365                              35036 non-null  int64
 66  calendar_last_scraped                         35036 non-null  str
 67  number_of_reviews                             35036 non-null  int64
 68  number_of_reviews_ltm                         35036 non-null  int64
 69  number_of_reviews_l30d                        35036 non-null  int64
 70  availability_eoy                              35036 non-null  int64
 71  number_of_reviews_ly                          35036 non-null  int64
 72  estimated_occupancy_l365d                     35036 non-null  int64
 73  estimated_revenue_l365d                       20693 non-null  float64
 74  first_review                                  24542 non-null  str
 75  last_review                                   24542 non-null  str
 76  review_scores_rating                          24542 non-null  float64
 77  review_scores_accuracy                        24532 non-null  float64
 78  review_scores_cleanliness                     24541 non-null  float64
 79  review_scores_checkin                         24528 non-null  float64
 80  review_scores_communication                   24536 non-null  float64
 81  review_scores_location                        24525 non-null  float64
 82  review_scores_value                           24526 non-null  float64
 83  license                                       5062 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                35036 non-null  int64
 86  calculated_host_listings_count_entire_homes   35036 non-null  int64
 87  calculated_host_listings_count_private_rooms  35036 non-null  int64
 88  calculated_host_listings_count_shared_rooms   35036 non-null  int64
 89  reviews_per_month                             24542 non-null  float64
dtypes: float64(42), int64(18), str(30)
memory usage: 24.1 MB

In [12]:
london_listings.head(3)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.87,4.78,4.78,NaN,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.93,4.74,NaN,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.89,4.61,NaN,f,2,2,0,0,0.32

In [13]:
ny_listings.head(3)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6848,https://www.airbnb.com/rooms/6848,20260414135910,2026-04-14,previous scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.59,NaN,NaN,1,1,0,0,0.96
1,6872,https://www.airbnb.com/rooms/6872,20260414135910,2026-04-14,previous scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.00,5.00,5.00,NaN,NaN,2,0,2,0,0.04
2,6990,https://www.airbnb.com/rooms/6990,20260414135910,2026-04-14,previous scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,NaN,https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.84,NaN,NaN,1,0,1,0,1.25

In [14]:
set(ny_listings.columns) - set(london_listings.columns)

{'host_profile_id',
 'host_profile_url',
 'hosts_time_as_host_months',
 'hosts_time_as_host_years',
 'hosts_time_as_user_months',
 'hosts_time_as_user_years',
 'price_quote_checkin_date',
 'price_quote_checkout_date',
 'price_quote_price_per_night',
 'price_quote_raw',
 'price_quote_total_price'}

In [15]:
set(london_listings.columns) - set(ny_listings.columns)

set()

In [16]:
print("LONDON CALENDAR")
print(london_calendar.columns.tolist())

print("\nLONDON REVIEWS")
print(london_reviews.columns.tolist())

print("\nLONDON NEIGHBOURHOODS")
print(london_neighbourhoods.columns.tolist())

print("\nNY CALENDAR")
print(ny_calendar.columns.tolist())

print("\nNY REVIEWS")
print(ny_reviews.columns.tolist())

print("\nNY NEIGHBOURHOODS")
print(ny_neighbourhoods.columns.tolist())

LONDON CALENDAR
['listing_id', 'date', 'available', 'price', 'adjusted_price', 'minimum_nights', 'maximum_nights']

LONDON REVIEWS
['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments']

LONDON NEIGHBOURHOODS
['neighbourhood_group', 'neighbourhood']

NY CALENDAR
['listing_id', 'date', 'available', 'minimum_nights', 'maximum_nights']

NY REVIEWS
['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments']

NY NEIGHBOURHOODS
['neighbourhood_group', 'neighbourhood']

In [17]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.memory_usage(deep=True).sum() / 1024**2, "MB")

London Listings
394.6103324890137 MB

London Calendar
5563.798753738403 MB

London Reviews
1099.951955795288 MB

London Neighbourhoods
0.0024881362915039062 MB

NY Listings
140.72825813293457 MB

NY Calendar
1817.1626482009888 MB

NY Reviews
530.2015447616577 MB

NY Neighbourhoods
0.029388427734375 MB